import type { Product, Coupon, Address, RawProduct } from './types';

// Product Categories
export const CATEGORIES = [
  'Electronics',
  'Fashion',
  'Home & Living',
  'Sports',
  'Books',
  'Beauty',
  'Toys',
  'Grocery',
];

export const SUBCATEGORIES: Record<string, string[]> = {
  Electronics: ['Mobiles', 'Laptops', 'Tablets', 'Headphones', 'Cameras', 'Smartwatches'],
  Fashion: ['Men', 'Women', 'Kids', 'Footwear', 'Accessories', 'Sports Wear'],
  'Home & Living': ['Furniture', 'Decor', 'Bedding', 'Kitchenware', 'Lighting'],
  Sports: ['Fitness', 'Outdoor', 'Team Sports', 'Water Sports'],
  Books: ['Fiction', 'Non-Fiction', 'Educational', 'Comics'],
  Beauty: ['Skincare', 'Makeup', 'Hair Care', 'Personal Care'],
  Toys: ['Dolls', 'Action Figures', 'Puzzles', 'Board Games'],
  Grocery: ['Vegetables', 'Fruits', 'Dairy', 'Snacks', 'Beverages'],
};

// 100+ Products
export const RAW_PRODUCTS: RawProduct[] = [
  // Electronics - Mobiles
  {
    id: 'ce1a134e-a883-4799-b248-1cfb93dd1972',
    name: 'Apple iPhone 17 Pro Max (Cosmic Orange, 512 GB)',
    description: 'Buy Apple iPhone 17 Pro Max online at best price with offers in India. Apple iPhone 17 Pro Max (Cosmic Orange, 512 GB) features and specifications include 512 GB ROM, 48 MP back camera and 18 MP front camera. Compare iPhone 17 Pro Max by price and performance to shop at Flipkart',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Apple',
    price: 999,
    originalPrice: 169900,
    discount: 25,
    rating: 4.8,
    reviews: 102,
    stock: 45,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/f/v/m/-original-imahft6chnx2vbuy.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/m/n/c/-original-imahft6c3rbjysmg.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/t/1/p/-original-imahft6cag2fggja.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/b/o/v/-original-imahft6cvnadukgx.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/x/c/q/-original-imahft5njwbfyz5u.jpeg?q=70"],
    specs: {
      'Display': '6.7" Super Retina XDR',
      'Camera': '48MP Main + 12MP Ultra Wide',
      'Processor': 'A17 Pro',
      'Battery': '4685 mAh',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: '2696b48e-a4b5-45dc-b397-55c6cdace35e',
    name: 'Samsung Galaxy S26 Ultra 5G (Cobalt Violet, 512 GB)',
    description: 'Buy Samsung Galaxy S26 Ultra 5G online at best price with offers in India. Samsung Galaxy S26 Ultra 5G (Cobalt Violet, 512 GB) features and specifications include 12 GB RAM, 512 GB ROM, 5000 mAh Battery, 200 MP back camera and 12 MP front camera. Compare Galaxy S26 Ultra 5G by price and performance to shop at Flipkart',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Samsung',
    price: 999,
    originalPrice: 159999,
    discount: 23,
    rating: 4.7,
    reviews: 354,
    stock: 62,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/y/t/3/-original-imahhyzrqqfs6yvp.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/e/5/c/-original-imahhyzrq5bnsyar.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/b/d/e/-original-imahnmndrkpry4ge.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/k/q/m/-original-imahhyzrdnnzuznj.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/i/c/n/-original-imahhyzrpdrvrgpk.jpeg?q=70"],
    specs: {
      'Display': '6.8" Dynamic AMOLED',
      'Camera': '50MP Main + 200MP Telephoto',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5000 mAh',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: 'fed15621-3cc1-4526-91f8-2adb76c5a20e',
    name: 'Apple iPhone Air (Sky Blue, 512 GB)',
    description: 'Buy Apple iPhone Air online at best price with offers in India. Apple iPhone Air (Sky Blue, 512 GB) features and specifications include 512 GB ROM, 48 MP back camera and 18 MP front camera. Compare iPhone Air by price and performance to shop at Flipkart',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Apple',
    price: 999,
    originalPrice: 139900,
    discount: 23,
    rating: 4.6,
    reviews: 9,
    stock: 38,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/5/p/i/-original-imahft57t6g4d5bj.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/b/g/g/-original-imahft57yarshdvs.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/d/2/m/-original-imahft57p4nqwryz.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/x/8/n/-original-imahft57wfmtquq3.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/5/i/q/-original-imahft57gjxhemup.jpeg?q=70"],
    specs: {
      'Display': '6.7" QHD+ OLED',
      'Camera': '50MP Main + 48MP Telephoto',
      'Processor': 'Tensor G3',
      'Battery': '5050 mAh',
    },
    warranty: '2 Years',
    delivery: 'Next Day',
  },
  {
    id: '4e593814-74db-4bc4-91b3-6920b2c5d05e',
    name: 'Apple MacBook Air (M5, 2026) M5 - (16 GB/512 GB SSD/Tahoe) MDVQ4HN/A',
    description: 'Buy Apple MacBook Air (M5, 2026) M5 - (16 GB/512 GB SSD/Tahoe) MDVQ4HN/A Online For Rs.144900.0 , Also get Apple MacBook Air (M5, 2026) M5 - (16 GB/512 GB SSD/Tahoe) MDVQ4HN/A Specifications & Features. Only Genuine Products. 30 Day Replacement Guarantee. Free Shipping. Cash On Delivery!',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    price: 1299,
    originalPrice: 144900,
    discount: 25,
    rating: 4.5,
    reviews: 3421,
    stock: 85,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/computer/b/x/k/-original-imahh84y2yruym9f.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/computer/z/x/a/-original-imahh84ynmwdnqzh.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/computer/n/i/v/-original-imahh84yub2xvhmg.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/computer/v/n/x/-original-imahh84ybg4p8uvp.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/computer/3/j/c/-original-imahh84yx9zep96a.jpeg?q=70"],
    specs: {
      'Display': '13.6" AMOLED',
      'Camera': '50MP Main + 12MP Ultra Wide',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5400 mAh',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: '8e7f93de-ae10-4617-9479-a75e85416cc2',
    name: 'Apple iPhone 15 Pro (Blue Titanium, 512 GB)',
    description: '"Buy Apple iPhone 15 Pro online at best price with offers in India. Apple iPhone 15 Pro (Blue Titanium, 512 GB) features and specifications include 512 GB ROM, 48 MP back camera and 12 MP front camera. Compare iPhone 15 Pro by price and performance to shop at Flipkart',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Apple',
    price: 1299,
    originalPrice: 175000,
    discount: 29,
    rating: 4.7,
    reviews: 156,
    stock: 120,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/z/4/r/-original-imagtc4g22rcatjg.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/r/t/r/-original-imagtc4gtzyretcs.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/d/m/n/-original-imagtc4gmpfhfzky.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/7/e/s/-original-imagtc3kknyq2b95.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/1/5/a/-original-imagtc4gjqfnarcs.jpeg?q=70"],
    specs: {
      'Display': '6.73" AMOLED',
      'Camera': '50MP Main + 50MP Ultra Wide',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5300 mAh',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },

  // Electronics - Laptops
  {
    id: 'b2019bf8-2652-4030-9dc2-c9d91849500f',
    name: 'Apple Watch Series 11 GPS 42mm Jet Black Aluminium Case Black Sport Band - S/M',
    description: 'Buy Apple Watch Series 11 GPS 42mm Jet Black Aluminium Case Black Sport Band - S/M for Rs.46900.0 online. Apple Watch Series 11 GPS 42mm Jet Black Aluminium Case Black Sport Band - S/M at best prices with FREE shipping & cash on delivery. Only Genuine Products. 30 Day Replacement Guarantee.',
    category: 'Electronics',
    subcategory: 'Smart Watches',
    brand: 'Apple',
    price: 499,
    originalPrice: 46900,
    discount: 29,
    rating: 4.6,
    reviews: 8,
    stock: 22,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/smartwatch/9/a/f/-original-imahftgghqzgbfth.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/smartwatch/r/h/r/-original-imahftggha9ppr6w.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/smartwatch/k/z/t/-original-imahftghwpab7hpy.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/smartwatch/m/h/z/-original-imahftggxdkr7my6.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/smartwatch/x/1/c/-original-imahftggzvx2gywe.jpeg?q=70"],
    specs: {
      'Display': '42 mm Display',
      'Processor': 'Apple M3 Max',
      'Bluetooth': 'With Bluetooth',
      'Calling': 'With Calling Feature',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: '2f3796c2-0492-4e9b-9acb-ccbff9586d1e',
    name: 'Apple iPhone 16 Plus (Ultramarine, 256 GB)',
    description: 'Buy Apple iPhone 16 Plus online at best price with offers in India. Apple iPhone 16 Plus (Ultramarine, 256 GB) features and specifications include 256 GB ROM, 48 MP back camera and 12 MP front camera. Compare iPhone 16 Plus by price and performance to shop at Flipkart',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Apple',
    price: 999,
    originalPrice: 95000,
    discount: 27,
    rating: 4.6,
    reviews: 252,
    stock: 35,
    images: ["https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/o/d/1/-original-imahggetmzzanrty.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/c/w/c/-original-imahggetwef2gpyt.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/p/m/u/-original-imahfvx3ynz4zqeg.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/v/d/w/-original-imahggetywewkhrg.jpeg?q=70",
      "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mobile/j/o/f/-original-imahfvx3gfzzy2uk.jpeg?q=70"],
    specs: {
      'Display': '15.6" OLED',
      'Processor': 'Intel Core i7',
      'RAM': '32GB',
      'Storage': '512GB SSD',
    },
    warranty: '2 Years',
    delivery: 'Next Day',
  },
  {
    id: 'prod_008',
    name: 'HP Pavilion 15',
    description: 'Affordable laptop for everyday use',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'HP',
    price: 49999,
    originalPrice: 79999,
    discount: 38,
    rating: 4.3,
    reviews: 892,
    stock: 67,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Display': '15.6" FHD',
      'Processor': 'Intel Core i5',
      'RAM': '8GB',
      'Storage': '256GB SSD',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_009',
    name: 'ASUS VivoBook 15',
    description: 'Lightweight and portable',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'ASUS',
    price: 42999,
    originalPrice: 69999,
    discount: 39,
    rating: 4.2,
    reviews: 645,
    stock: 78,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Display': '15.6" FHD',
      'Processor': 'AMD Ryzen 5',
      'RAM': '8GB',
      'Storage': '512GB SSD',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_010',
    name: 'Lenovo ThinkPad E15',
    description: 'Business laptop with reliability',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Lenovo',
    price: 64999,
    originalPrice: 99999,
    discount: 35,
    rating: 4.4,
    reviews: 521,
    stock: 45,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Display': '15.6" IPS FHD',
      'Processor': 'Intel Core i7',
      'RAM': '16GB',
      'Storage': '512GB SSD',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },

  // Electronics - Headphones
  {
    id: 'prod_011',
    name: 'Sony WH-1000XM5',
    description: 'Best noise-cancelling headphones',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    price: 29999,
    originalPrice: 39999,
    discount: 25,
    rating: 4.8,
    reviews: 3456,
    stock: 142,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '30 hours',
      'Weight': '250g',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_012',
    name: 'Bose QuietComfort Ultra Headphones',
    description: 'Premium comfort and sound',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Bose',
    price: 34999,
    originalPrice: 49999,
    discount: 30,
    rating: 4.7,
    reviews: 2134,
    stock: 89,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '24 hours',
      'Weight': '226g',
    },
    warranty: '2 Years',
    delivery: 'Same Day',
  },
  {
    id: 'prod_013',
    name: 'JBL Live 660NC',
    description: 'Budget-friendly with good quality',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'JBL',
    price: 9999,
    originalPrice: 19999,
    discount: 50,
    rating: 4.2,
    reviews: 1823,
    stock: 267,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.0',
      'Battery': '36 hours',
      'Weight': '205g',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_014',
    name: 'Sennheiser Momentum 4',
    description: 'Long battery life headphones',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sennheiser',
    price: 27999,
    originalPrice: 39999,
    discount: 30,
    rating: 4.6,
    reviews: 945,
    stock: 123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.2',
      'Battery': '60 hours',
      'Weight': '349g',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_015',
    name: 'Apple AirPods Max',
    description: 'Spatial audio experience',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Apple',
    price: 54999,
    originalPrice: 64999,
    discount: 15,
    rating: 4.5,
    reviews: 1267,
    stock: 78,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '20 hours',
      'Weight': '384.8g',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Fashion - Men
  {
    id: 'prod_016',
    name: 'Nike Air Jordan 1 Retro High',
    description: 'Iconic sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Nike',
    price: 15999,
    originalPrice: 22999,
    discount: 30,
    rating: 4.6,
    reviews: 4523,
    stock: 234,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Material': 'Leather + Synthetic',
      'Size': '6-13',
      'Color': 'Black/Red',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_017',
    name: 'Adidas Stan Smith',
    description: 'Classic white sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Adidas',
    price: 6999,
    originalPrice: 9999,
    discount: 30,
    rating: 4.4,
    reviews: 3456,
    stock: 456,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'Canvas + Leather',
      'Size': '5-14',
      'Color': 'White',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },
  {
    id: 'prod_018',
    name: 'Puma RS-X',
    description: 'Retro style sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Puma',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    rating: 4.3,
    reviews: 2345,
    stock: 345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'Synthetic + Mesh',
      'Size': '6-12',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_019',
    name: 'Boat Lifestyle Watch',
    description: 'Smart watch with fitness tracking',
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'Boat',
    price: 4999,
    originalPrice: 9999,
    discount: 50,
    rating: 4.2,
    reviews: 2156,
    stock: 567,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5ATM',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_020',
    name: 'Fastrack Men Watch',
    description: 'Casual analog watch',
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'Fastrack',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.1,
    reviews: 1834,
    stock: 789,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Display': 'Analog',
      'Material': 'Metal + Leather',
      'Water Resistance': '3ATM',
    },
    warranty: '2 Years',
    delivery: '3 Days',
  },

  // Home & Living
  {
    id: 'prod_021',
    name: 'IKEA Sofa Bed',
    description: 'Space-saving furniture',
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'IKEA',
    price: 24999,
    originalPrice: 39999,
    discount: 37,
    rating: 4.3,
    reviews: 567,
    stock: 45,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Material': 'Fabric',
      'Dimensions': '200x90x70 cm',
      'Color': 'Gray',
    },
    warranty: '2 Years',
    delivery: '5 Days',
  },
  {
    id: 'prod_022',
    name: 'Godrej Wardrobe',
    description: 'Spacious bedroom storage',
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'Godrej',
    price: 14999,
    originalPrice: 24999,
    discount: 40,
    rating: 4.2,
    reviews: 423,
    stock: 67,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'Engineered Wood',
      'Dimensions': '170x220x50 cm',
      'Color': 'Walnut',
    },
    warranty: '3 Years',
    delivery: '5 Days',
  },
  {
    id: 'prod_023',
    name: 'Decathlon Yoga Mat',
    description: 'Non-slip exercise mat',
    category: 'Home & Living',
    subcategory: 'Decor',
    brand: 'Decathlon',
    price: 799,
    originalPrice: 1499,
    discount: 47,
    rating: 4.4,
    reviews: 2134,
    stock: 1234,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'TPE',
      'Thickness': '6mm',
      'Color': 'Purple',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_024',
    name: 'Philips Smart Bulb',
    description: 'WiFi enabled LED bulb',
    category: 'Home & Living',
    subcategory: 'Lighting',
    brand: 'Philips',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.6,
    reviews: 3456,
    stock: 2345,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Power': '9W',
      'Color': 'RGB',
      'Connectivity': 'WiFi',
    },
    warranty: '2 Years',
    delivery: 'Same Day',
  },
  {
    id: 'prod_025',
    name: 'Prestige Pressure Cooker',
    description: 'Stainless steel pressure cooker',
    category: 'Home & Living',
    subcategory: 'Kitchenware',
    brand: 'Prestige',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.5,
    reviews: 2456,
    stock: 890,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Capacity': '5L',
      'Material': 'Stainless Steel',
      'Type': 'Cooker',
    },
    warranty: '5 Years',
    delivery: '2 Days',
  },

  // Books
  {
    id: 'prod_026',
    name: 'Atomic Habits',
    description: 'Build better habits',
    category: 'Books',
    subcategory: 'Non-Fiction',
    brand: 'Penguin',
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.9,
    reviews: 5678,
    stock: 4567,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Author': 'James Clear',
      'Pages': '320',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_027',
    name: 'The Silent Patient',
    description: 'Psychological thriller',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Penguin',
    price: 349,
    originalPrice: 549,
    discount: 36,
    rating: 4.7,
    reviews: 3456,
    stock: 2345,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Author': 'Alex Michaelides',
      'Pages': '368',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_028',
    name: 'Wings of Fire Series',
    description: 'Popular YA fantasy series',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Scholastic',
    price: 299,
    originalPrice: 449,
    discount: 33,
    rating: 4.8,
    reviews: 2123,
    stock: 3456,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Author': 'Tui T. Sutherland',
      'Pages': '368',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: '2 Days',
  },
  {
    id: 'prod_029',
    name: 'Sapiens',
    description: 'History of humankind',
    category: 'Books',
    subcategory: 'Non-Fiction',
    brand: 'Penguin',
    price: 599,
    originalPrice: 899,
    discount: 33,
    rating: 4.8,
    reviews: 4567,
    stock: 2123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Author': 'Yuval Noah Harari',
      'Pages': '443',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_030',
    name: 'Harry Potter Box Set',
    description: 'Complete series collection',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Bloomsbury',
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    rating: 4.9,
    reviews: 6234,
    stock: 1234,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Author': 'J.K. Rowling',
      'Books': '7',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: '2 Days',
  },

  // Beauty
  {
    id: 'prod_031',
    name: 'Lakme Sunscreen SPF 50',
    description: 'Daily sun protection',
    category: 'Beauty',
    subcategory: 'Skincare',
    brand: 'Lakme',
    price: 299,
    originalPrice: 449,
    discount: 33,
    rating: 4.3,
    reviews: 1234,
    stock: 4567,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'SPF': '50',
      'Size': '50g',
      'Type': 'Cream',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_032',
    name: 'Maybelline Mascara',
    description: 'Volumizing mascara',
    category: 'Beauty',
    subcategory: 'Makeup',
    brand: 'Maybelline',
    price: 349,
    originalPrice: 549,
    discount: 36,
    rating: 4.4,
    reviews: 2345,
    stock: 3456,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Finish': 'Volumizing',
      'Size': '9.2ml',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_033',
    name: 'L\'Oreal Shampoo',
    description: 'Hair care shampoo',
    category: 'Beauty',
    subcategory: 'Hair Care',
    brand: 'L\'Oreal',
    price: 399,
    originalPrice: 649,
    discount: 38,
    rating: 4.5,
    reviews: 1890,
    stock: 2345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Size': '250ml',
      'Type': 'Shampoo',
      'For': 'All Hair Types',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },
  {
    id: 'prod_034',
    name: 'Cetaphil Face Wash',
    description: 'Gentle cleanser',
    category: 'Beauty',
    subcategory: 'Skincare',
    brand: 'Cetaphil',
    price: 449,
    originalPrice: 649,
    discount: 31,
    rating: 4.6,
    reviews: 2456,
    stock: 3123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Size': '200g',
      'Type': 'Face Wash',
      'For': 'Sensitive Skin',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_035',
    name: 'MAC Lipstick',
    description: 'Premium lipstick',
    category: 'Beauty',
    subcategory: 'Makeup',
    brand: 'MAC',
    price: 1899,
    originalPrice: 2799,
    discount: 32,
    rating: 4.7,
    reviews: 1567,
    stock: 789,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '3g',
      'Finish': 'Satin',
      'Color': 'Red',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Sports
  {
    id: 'prod_036',
    name: 'Decathlon Dumbbells',
    description: 'Home gym equipment',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'Decathlon',
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.5,
    reviews: 1234,
    stock: 890,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Weight': '10kg',
      'Material': 'Iron',
      'Set': 'Pair',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_037',
    name: 'Yoga Block Set',
    description: 'Exercise support blocks',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'Decathlon',
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.4,
    reviews: 890,
    stock: 1234,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'EVA Foam',
      'Quantity': '3',
      'Color': 'Purple',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_038',
    name: 'Ajay Cricket Bat',
    description: 'Professional grade bat',
    category: 'Sports',
    subcategory: 'Team Sports',
    brand: 'Ajay',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.6,
    reviews: 567,
    stock: 234,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'English Willow',
      'Weight': '1.2kg',
      'Length': '37.5 inches',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_039',
    name: 'Badminton Racket',
    description: 'Lightweight carbon racket',
    category: 'Sports',
    subcategory: 'Team Sports',
    brand: 'Yonex',
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.5,
    reviews: 456,
    stock: 345,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Material': 'Carbon Composite',
      'Weight': '80g',
      'Grip Size': 'G4',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_040',
    name: 'Swimming Goggles',
    description: 'Anti-fog goggles',
    category: 'Sports',
    subcategory: 'Water Sports',
    brand: 'Speedo',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.4,
    reviews: 678,
    stock: 567,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Lens': 'Anti-fog',
      'Frame': 'Silicone',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },

  // Toys
  {
    id: 'prod_041',
    name: 'LEGO City Police Station',
    description: 'Building block set',
    category: 'Toys',
    subcategory: 'Building Sets',
    brand: 'LEGO',
    price: 4999,
    originalPrice: 7999,
    discount: 38,
    rating: 4.7,
    reviews: 2345,
    stock: 456,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Pieces': '967',
      'Age': '5+',
      'Brand': 'LEGO',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_042',
    name: 'Hot Wheels Car Set',
    description: 'Toy car collection',
    category: 'Toys',
    subcategory: 'Vehicles',
    brand: 'Hot Wheels',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.5,
    reviews: 1234,
    stock: 890,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Cars': '10',
      'Age': '3+',
      'Material': 'Die-cast Metal',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_043',
    name: 'Scrabble Board Game',
    description: 'Word building game',
    category: 'Toys',
    subcategory: 'Board Games',
    brand: 'Hasbro',
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.6,
    reviews: 678,
    stock: 345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Players': '2-4',
      'Age': '8+',
      'Duration': '60 min',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_044',
    name: 'Barbie Doll',
    description: 'Fashion doll',
    category: 'Toys',
    subcategory: 'Dolls',
    brand: 'Mattel',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    rating: 4.4,
    reviews: 567,
    stock: 567,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Height': '29cm',
      'Age': '3+',
      'Accessories': 'Yes',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_045',
    name: 'Rubik\'s Cube',
    description: 'Classic puzzle cube',
    category: 'Toys',
    subcategory: 'Puzzles',
    brand: 'Rubik\'s',
    price: 349,
    originalPrice: 599,
    discount: 42,
    rating: 4.7,
    reviews: 1234,
    stock: 2345,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '5.7cm',
      'Age': '8+',
      'Type': '3x3',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Grocery
  {
    id: 'prod_046',
    name: 'Basmati Rice 5kg',
    description: 'Premium long grain rice',
    category: 'Grocery',
    subcategory: 'Staples',
    brand: 'India Gate',
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.5,
    reviews: 2345,
    stock: 5678,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Type': 'Basmati',
      'Weight': '5kg',
      'Origin': 'India',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_047',
    name: 'Organic Honey',
    description: 'Pure raw honey',
    category: 'Grocery',
    subcategory: 'Sweeteners',
    brand: 'Nature\'s Blessing',
    price: 599,
    originalPrice: 899,
    discount: 33,
    rating: 4.6,
    reviews: 1234,
    stock: 890,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Type': 'Organic',
      'Weight': '500g',
      'Purity': '100%',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_048',
    name: 'Milk Powder',
    description: 'Nutritious milk powder',
    category: 'Grocery',
    subcategory: 'Dairy',
    brand: 'Amul',
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.4,
    reviews: 890,
    stock: 3456,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Type': 'Full Fat',
      'Weight': '400g',
      'Shelf Life': '18 months',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_049',
    name: 'Olive Oil Premium',
    description: 'Extra virgin olive oil',
    category: 'Grocery',
    subcategory: 'Oils',
    brand: 'Borges',
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.7,
    reviews: 678,
    stock: 456,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Type': 'Extra Virgin',
      'Size': '500ml',
      'Origin': 'Spain',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_050',
    name: 'Coca Cola 1L Bottle',
    description: 'Refreshing beverage',
    category: 'Grocery',
    subcategory: 'Beverages',
    brand: 'Coca Cola',
    price: 59,
    originalPrice: 99,
    discount: 40,
    rating: 4.3,
    reviews: 1234,
    stock: 9876,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '1L',
      'Type': 'Soft Drink',
      'Packaging': 'Bottle',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
];
export const PRODUCTS: Product[] = RAW_PRODUCTS.slice(0, 7).map((product, index) => ({
  ...product,

  categoryId: product.category
    .toLowerCase()
    .replace(/\s*&\s*/g, '-')
    .replace(/\s+/g, '-'),

  image: product.images[0],

  discount: 99,

  thumbnail: product.images[0],

  createdAt: new Date(),

  seller: {
    id: `seller_${String((index % 5) + 1).padStart(3, '0')}`,
    name: 'Visionary Store',
    verified: true,
    rating: 4.5,
  },

  seoTitle: product.name,
  seoDescription: product.description,

  isFeatured: product.rating >= 4,

  isTrending:
    product.reviews > 3000,

  isNewArrival: false,

  fastDelivery: [
    'Same Day',
    'Next Day',
  ].includes(product.delivery),

  badges: [
    ...(product.rating >= 4.7
      ? ['Top Rated']
      : []),
    ...(product.discount >= 40
      ? ['Great Deal']
      : []),
  ],

  color: product.specs.Color || '',
  size: product.specs.Size || '',

  sku: `SKU-${product.id.toUpperCase()}`,
}));

// Coupons
export const COUPONS: Coupon[] = [
  {
    id: 'coup_001',
    code: 'WELCOME50',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 500,
    maxDiscount: 500,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 1000,
    used: 234,
    isActive: true,
  },
  {
    id: 'coup_002',
    code: 'FLAT500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderValue: 2000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 500,
    used: 123,
    isActive: true,
  },
  {
    id: 'coup_003',
    code: 'ELECTRONICS25',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 5000,
    maxDiscount: 2000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 300,
    used: 145,
    isActive: true,
  },
  {
    id: 'coup_004',
    code: 'FASHION30',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 1000,
    maxDiscount: 1000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 400,
    used: 267,
    isActive: true,
  },
  {
    id: 'coup_005',
    code: 'BOOKS40',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 300,
    maxDiscount: 300,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 600,
    used: 389,
    isActive: true,
  },
];

// Default Addresses
export const DEFAULT_ADDRESSES: Address[] = [
  {
    id: 'addr_001',
    type: 'home',
    name: 'Home',
    phone: '9876543210',
    street: '123 Main Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    isDefault: true,
  },
  {
    id: 'addr_002',
    type: 'work',
    name: 'Office',
    phone: '9876543210',
    street: '456 Business Park',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400005',
    isDefault: false,
  },
];

// Filter options
export const PRICE_RANGES = [
  { label: 'Under ₹500', min: 0, max: 500 },
  { label: '₹500 - ₹2000', min: 500, max: 2000 },
  { label: '₹2000 - ₹10000', min: 2000, max: 10000 },
  { label: '₹10000 - ₹50000', min: 10000, max: 50000 },
  { label: 'Above ₹50000', min: 50000, max: Infinity },
];

export const BRANDS = Array.from(new Set(PRODUCTS.map(p => p.brand))).sort();
export const RATING_FILTERS = [
  { label: '4★ & above', min: 4 },
  { label: '3★ & above', min: 3 },
  { label: '2★ & above', min: 2 },
];
