import type { Product, Coupon, Address, RawProduct } from './types';

// Product Categories
export const CATEGORIES = [
  'Electronics',
  'Fashion',
  'Home & Living',
  'Sports',
  'Books',
  'Beauty',
  'Toys',
  'Grocery',
];

export const SUBCATEGORIES: Record<string, string[]> = {
  Electronics: ['Mobiles', 'Laptops', 'Tablets', 'Headphones', 'Cameras', 'Smartwatches'],
  Fashion: ['Men', 'Women', 'Kids', 'Footwear', 'Accessories', 'Sports Wear'],
  'Home & Living': ['Furniture', 'Decor', 'Bedding', 'Kitchenware', 'Lighting'],
  Sports: ['Fitness', 'Outdoor', 'Team Sports', 'Water Sports'],
  Books: ['Fiction', 'Non-Fiction', 'Educational', 'Comics'],
  Beauty: ['Skincare', 'Makeup', 'Hair Care', 'Personal Care'],
  Toys: ['Dolls', 'Action Figures', 'Puzzles', 'Board Games'],
  Grocery: ['Vegetables', 'Fruits', 'Dairy', 'Snacks', 'Beverages'],
};

// 100+ Products
export const RAW_PRODUCTS: RawProduct[] = [
  // Electronics - Mobiles
  {
    id: 'prod_001',
    name: 'iPhone 15 Pro Max',
    description: 'Latest Apple flagship with advanced features',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Apple',
    price: 119999,
    originalPrice: 159999,
    discount: 25,
    rating: 4.8,
    reviews: 5234,
    stock: 45,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Display': '6.7" Super Retina XDR',
      'Camera': '48MP Main + 12MP Ultra Wide',
      'Processor': 'A17 Pro',
      'Battery': '4685 mAh',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: 'prod_002',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Powerful Android flagship smartphone',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Samsung',
    price: 99999,
    originalPrice: 129999,
    discount: 23,
    rating: 4.7,
    reviews: 4156,
    stock: 62,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Display': '6.8" Dynamic AMOLED',
      'Camera': '50MP Main + 200MP Telephoto',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5000 mAh',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: 'prod_003',
    name: 'Google Pixel 8 Pro',
    description: 'AI-powered smartphone with exceptional camera',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Google',
    price: 84999,
    originalPrice: 109999,
    discount: 23,
    rating: 4.6,
    reviews: 2834,
    stock: 38,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Display': '6.7" QHD+ OLED',
      'Camera': '50MP Main + 48MP Telephoto',
      'Processor': 'Tensor G3',
      'Battery': '5050 mAh',
    },
    warranty: '2 Years',
    delivery: 'Next Day',
  },
  {
    id: 'prod_004',
    name: 'OnePlus 12',
    description: 'Fast and smooth Android experience',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'OnePlus',
    price: 59999,
    originalPrice: 79999,
    discount: 25,
    rating: 4.5,
    reviews: 3421,
    stock: 85,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Display': '6.7" AMOLED',
      'Camera': '50MP Main + 48MP Telephoto',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5400 mAh',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_005',
    name: 'Xiaomi 14 Ultra',
    description: 'Value for money flagship killer',
    category: 'Electronics',
    subcategory: 'Mobiles',
    brand: 'Xiaomi',
    price: 49999,
    originalPrice: 69999,
    discount: 29,
    rating: 4.4,
    reviews: 2156,
    stock: 120,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Display': '6.73" AMOLED',
      'Camera': '50MP Main + 50MP Ultra Wide',
      'Processor': 'Snapdragon 8 Gen 3',
      'Battery': '5300 mAh',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },

  // Electronics - Laptops
  {
    id: 'prod_006',
    name: 'MacBook Pro 16" M3 Max',
    description: 'Professional laptop for creators',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    price: 249999,
    originalPrice: 349999,
    discount: 29,
    rating: 4.9,
    reviews: 1834,
    stock: 22,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Display': '16" Liquid Retina XDR',
      'Processor': 'Apple M3 Max',
      'RAM': '36GB',
      'Storage': '512GB SSD',
    },
    warranty: '1 Year',
    delivery: 'Next Day',
  },
  {
    id: 'prod_007',
    name: 'Dell XPS 15',
    description: 'Premium Windows laptop',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Dell',
    price: 159999,
    originalPrice: 219999,
    discount: 27,
    rating: 4.7,
    reviews: 1256,
    stock: 35,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Display': '15.6" OLED',
      'Processor': 'Intel Core i7',
      'RAM': '32GB',
      'Storage': '512GB SSD',
    },
    warranty: '2 Years',
    delivery: 'Next Day',
  },
  {
    id: 'prod_008',
    name: 'HP Pavilion 15',
    description: 'Affordable laptop for everyday use',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'HP',
    price: 49999,
    originalPrice: 79999,
    discount: 38,
    rating: 4.3,
    reviews: 892,
    stock: 67,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Display': '15.6" FHD',
      'Processor': 'Intel Core i5',
      'RAM': '8GB',
      'Storage': '256GB SSD',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_009',
    name: 'ASUS VivoBook 15',
    description: 'Lightweight and portable',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'ASUS',
    price: 42999,
    originalPrice: 69999,
    discount: 39,
    rating: 4.2,
    reviews: 645,
    stock: 78,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Display': '15.6" FHD',
      'Processor': 'AMD Ryzen 5',
      'RAM': '8GB',
      'Storage': '512GB SSD',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_010',
    name: 'Lenovo ThinkPad E15',
    description: 'Business laptop with reliability',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Lenovo',
    price: 64999,
    originalPrice: 99999,
    discount: 35,
    rating: 4.4,
    reviews: 521,
    stock: 45,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Display': '15.6" IPS FHD',
      'Processor': 'Intel Core i7',
      'RAM': '16GB',
      'Storage': '512GB SSD',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },

  // Electronics - Headphones
  {
    id: 'prod_011',
    name: 'Sony WH-1000XM5',
    description: 'Best noise-cancelling headphones',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    price: 29999,
    originalPrice: 39999,
    discount: 25,
    rating: 4.8,
    reviews: 3456,
    stock: 142,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '30 hours',
      'Weight': '250g',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_012',
    name: 'Bose QuietComfort Ultra Headphones',
    description: 'Premium comfort and sound',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Bose',
    price: 34999,
    originalPrice: 49999,
    discount: 30,
    rating: 4.7,
    reviews: 2134,
    stock: 89,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '24 hours',
      'Weight': '226g',
    },
    warranty: '2 Years',
    delivery: 'Same Day',
  },
  {
    id: 'prod_013',
    name: 'JBL Live 660NC',
    description: 'Budget-friendly with good quality',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'JBL',
    price: 9999,
    originalPrice: 19999,
    discount: 50,
    rating: 4.2,
    reviews: 1823,
    stock: 267,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.0',
      'Battery': '36 hours',
      'Weight': '205g',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_014',
    name: 'Sennheiser Momentum 4',
    description: 'Long battery life headphones',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sennheiser',
    price: 27999,
    originalPrice: 39999,
    discount: 30,
    rating: 4.6,
    reviews: 945,
    stock: 123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.2',
      'Battery': '60 hours',
      'Weight': '349g',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_015',
    name: 'Apple AirPods Max',
    description: 'Spatial audio experience',
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Apple',
    price: 54999,
    originalPrice: 64999,
    discount: 15,
    rating: 4.5,
    reviews: 1267,
    stock: 78,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Noise Cancellation': 'Active',
      'Connectivity': 'Bluetooth 5.3',
      'Battery': '20 hours',
      'Weight': '384.8g',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Fashion - Men
  {
    id: 'prod_016',
    name: 'Nike Air Jordan 1 Retro High',
    description: 'Iconic sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Nike',
    price: 15999,
    originalPrice: 22999,
    discount: 30,
    rating: 4.6,
    reviews: 4523,
    stock: 234,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Material': 'Leather + Synthetic',
      'Size': '6-13',
      'Color': 'Black/Red',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_017',
    name: 'Adidas Stan Smith',
    description: 'Classic white sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Adidas',
    price: 6999,
    originalPrice: 9999,
    discount: 30,
    rating: 4.4,
    reviews: 3456,
    stock: 456,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'Canvas + Leather',
      'Size': '5-14',
      'Color': 'White',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },
  {
    id: 'prod_018',
    name: 'Puma RS-X',
    description: 'Retro style sneaker',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Puma',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    rating: 4.3,
    reviews: 2345,
    stock: 345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'Synthetic + Mesh',
      'Size': '6-12',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_019',
    name: 'Boat Lifestyle Watch',
    description: 'Smart watch with fitness tracking',
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'Boat',
    price: 4999,
    originalPrice: 9999,
    discount: 50,
    rating: 4.2,
    reviews: 2156,
    stock: 567,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5ATM',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_020',
    name: 'Fastrack Men Watch',
    description: 'Casual analog watch',
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'Fastrack',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.1,
    reviews: 1834,
    stock: 789,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Display': 'Analog',
      'Material': 'Metal + Leather',
      'Water Resistance': '3ATM',
    },
    warranty: '2 Years',
    delivery: '3 Days',
  },

  // Home & Living
  {
    id: 'prod_021',
    name: 'IKEA Sofa Bed',
    description: 'Space-saving furniture',
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'IKEA',
    price: 24999,
    originalPrice: 39999,
    discount: 37,
    rating: 4.3,
    reviews: 567,
    stock: 45,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Material': 'Fabric',
      'Dimensions': '200x90x70 cm',
      'Color': 'Gray',
    },
    warranty: '2 Years',
    delivery: '5 Days',
  },
  {
    id: 'prod_022',
    name: 'Godrej Wardrobe',
    description: 'Spacious bedroom storage',
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'Godrej',
    price: 14999,
    originalPrice: 24999,
    discount: 40,
    rating: 4.2,
    reviews: 423,
    stock: 67,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'Engineered Wood',
      'Dimensions': '170x220x50 cm',
      'Color': 'Walnut',
    },
    warranty: '3 Years',
    delivery: '5 Days',
  },
  {
    id: 'prod_023',
    name: 'Decathlon Yoga Mat',
    description: 'Non-slip exercise mat',
    category: 'Home & Living',
    subcategory: 'Decor',
    brand: 'Decathlon',
    price: 799,
    originalPrice: 1499,
    discount: 47,
    rating: 4.4,
    reviews: 2134,
    stock: 1234,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'TPE',
      'Thickness': '6mm',
      'Color': 'Purple',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_024',
    name: 'Philips Smart Bulb',
    description: 'WiFi enabled LED bulb',
    category: 'Home & Living',
    subcategory: 'Lighting',
    brand: 'Philips',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.6,
    reviews: 3456,
    stock: 2345,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Power': '9W',
      'Color': 'RGB',
      'Connectivity': 'WiFi',
    },
    warranty: '2 Years',
    delivery: 'Same Day',
  },
  {
    id: 'prod_025',
    name: 'Prestige Pressure Cooker',
    description: 'Stainless steel pressure cooker',
    category: 'Home & Living',
    subcategory: 'Kitchenware',
    brand: 'Prestige',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.5,
    reviews: 2456,
    stock: 890,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Capacity': '5L',
      'Material': 'Stainless Steel',
      'Type': 'Cooker',
    },
    warranty: '5 Years',
    delivery: '2 Days',
  },

  // Books
  {
    id: 'prod_026',
    name: 'Atomic Habits',
    description: 'Build better habits',
    category: 'Books',
    subcategory: 'Non-Fiction',
    brand: 'Penguin',
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.9,
    reviews: 5678,
    stock: 4567,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Author': 'James Clear',
      'Pages': '320',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_027',
    name: 'The Silent Patient',
    description: 'Psychological thriller',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Penguin',
    price: 349,
    originalPrice: 549,
    discount: 36,
    rating: 4.7,
    reviews: 3456,
    stock: 2345,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Author': 'Alex Michaelides',
      'Pages': '368',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_028',
    name: 'Wings of Fire Series',
    description: 'Popular YA fantasy series',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Scholastic',
    price: 299,
    originalPrice: 449,
    discount: 33,
    rating: 4.8,
    reviews: 2123,
    stock: 3456,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Author': 'Tui T. Sutherland',
      'Pages': '368',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: '2 Days',
  },
  {
    id: 'prod_029',
    name: 'Sapiens',
    description: 'History of humankind',
    category: 'Books',
    subcategory: 'Non-Fiction',
    brand: 'Penguin',
    price: 599,
    originalPrice: 899,
    discount: 33,
    rating: 4.8,
    reviews: 4567,
    stock: 2123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Author': 'Yuval Noah Harari',
      'Pages': '443',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: 'Same Day',
  },
  {
    id: 'prod_030',
    name: 'Harry Potter Box Set',
    description: 'Complete series collection',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Bloomsbury',
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    rating: 4.9,
    reviews: 6234,
    stock: 1234,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Author': 'J.K. Rowling',
      'Books': '7',
      'Language': 'English',
    },
    warranty: 'Lifetime',
    delivery: '2 Days',
  },

  // Beauty
  {
    id: 'prod_031',
    name: 'Lakme Sunscreen SPF 50',
    description: 'Daily sun protection',
    category: 'Beauty',
    subcategory: 'Skincare',
    brand: 'Lakme',
    price: 299,
    originalPrice: 449,
    discount: 33,
    rating: 4.3,
    reviews: 1234,
    stock: 4567,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'SPF': '50',
      'Size': '50g',
      'Type': 'Cream',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_032',
    name: 'Maybelline Mascara',
    description: 'Volumizing mascara',
    category: 'Beauty',
    subcategory: 'Makeup',
    brand: 'Maybelline',
    price: 349,
    originalPrice: 549,
    discount: 36,
    rating: 4.4,
    reviews: 2345,
    stock: 3456,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Finish': 'Volumizing',
      'Size': '9.2ml',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_033',
    name: 'L\'Oreal Shampoo',
    description: 'Hair care shampoo',
    category: 'Beauty',
    subcategory: 'Hair Care',
    brand: 'L\'Oreal',
    price: 399,
    originalPrice: 649,
    discount: 38,
    rating: 4.5,
    reviews: 1890,
    stock: 2345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Size': '250ml',
      'Type': 'Shampoo',
      'For': 'All Hair Types',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },
  {
    id: 'prod_034',
    name: 'Cetaphil Face Wash',
    description: 'Gentle cleanser',
    category: 'Beauty',
    subcategory: 'Skincare',
    brand: 'Cetaphil',
    price: 449,
    originalPrice: 649,
    discount: 31,
    rating: 4.6,
    reviews: 2456,
    stock: 3123,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Size': '200g',
      'Type': 'Face Wash',
      'For': 'Sensitive Skin',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_035',
    name: 'MAC Lipstick',
    description: 'Premium lipstick',
    category: 'Beauty',
    subcategory: 'Makeup',
    brand: 'MAC',
    price: 1899,
    originalPrice: 2799,
    discount: 32,
    rating: 4.7,
    reviews: 1567,
    stock: 789,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '3g',
      'Finish': 'Satin',
      'Color': 'Red',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Sports
  {
    id: 'prod_036',
    name: 'Decathlon Dumbbells',
    description: 'Home gym equipment',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'Decathlon',
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.5,
    reviews: 1234,
    stock: 890,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Weight': '10kg',
      'Material': 'Iron',
      'Set': 'Pair',
    },
    warranty: '1 Year',
    delivery: '3 Days',
  },
  {
    id: 'prod_037',
    name: 'Yoga Block Set',
    description: 'Exercise support blocks',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'Decathlon',
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.4,
    reviews: 890,
    stock: 1234,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Material': 'EVA Foam',
      'Quantity': '3',
      'Color': 'Purple',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_038',
    name: 'Ajay Cricket Bat',
    description: 'Professional grade bat',
    category: 'Sports',
    subcategory: 'Team Sports',
    brand: 'Ajay',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.6,
    reviews: 567,
    stock: 234,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Material': 'English Willow',
      'Weight': '1.2kg',
      'Length': '37.5 inches',
    },
    warranty: '6 Months',
    delivery: '3 Days',
  },
  {
    id: 'prod_039',
    name: 'Badminton Racket',
    description: 'Lightweight carbon racket',
    category: 'Sports',
    subcategory: 'Team Sports',
    brand: 'Yonex',
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.5,
    reviews: 456,
    stock: 345,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Material': 'Carbon Composite',
      'Weight': '80g',
      'Grip Size': 'G4',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_040',
    name: 'Swimming Goggles',
    description: 'Anti-fog goggles',
    category: 'Sports',
    subcategory: 'Water Sports',
    brand: 'Speedo',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.4,
    reviews: 678,
    stock: 567,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Lens': 'Anti-fog',
      'Frame': 'Silicone',
      'Color': 'Black',
    },
    warranty: '6 Months',
    delivery: '2 Days',
  },

  // Toys
  {
    id: 'prod_041',
    name: 'LEGO City Police Station',
    description: 'Building block set',
    category: 'Toys',
    subcategory: 'Building Sets',
    brand: 'LEGO',
    price: 4999,
    originalPrice: 7999,
    discount: 38,
    rating: 4.7,
    reviews: 2345,
    stock: 456,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Pieces': '967',
      'Age': '5+',
      'Brand': 'LEGO',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_042',
    name: 'Hot Wheels Car Set',
    description: 'Toy car collection',
    category: 'Toys',
    subcategory: 'Vehicles',
    brand: 'Hot Wheels',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.5,
    reviews: 1234,
    stock: 890,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Cars': '10',
      'Age': '3+',
      'Material': 'Die-cast Metal',
    },
    warranty: '1 Year',
    delivery: '2 Days',
  },
  {
    id: 'prod_043',
    name: 'Scrabble Board Game',
    description: 'Word building game',
    category: 'Toys',
    subcategory: 'Board Games',
    brand: 'Hasbro',
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.6,
    reviews: 678,
    stock: 345,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Players': '2-4',
      'Age': '8+',
      'Duration': '60 min',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_044',
    name: 'Barbie Doll',
    description: 'Fashion doll',
    category: 'Toys',
    subcategory: 'Dolls',
    brand: 'Mattel',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    rating: 4.4,
    reviews: 567,
    stock: 567,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Height': '29cm',
      'Age': '3+',
      'Accessories': 'Yes',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_045',
    name: 'Rubik\'s Cube',
    description: 'Classic puzzle cube',
    category: 'Toys',
    subcategory: 'Puzzles',
    brand: 'Rubik\'s',
    price: 349,
    originalPrice: 599,
    discount: 42,
    rating: 4.7,
    reviews: 1234,
    stock: 2345,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '5.7cm',
      'Age': '8+',
      'Type': '3x3',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },

  // Grocery
  {
    id: 'prod_046',
    name: 'Basmati Rice 5kg',
    description: 'Premium long grain rice',
    category: 'Grocery',
    subcategory: 'Staples',
    brand: 'India Gate',
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.5,
    reviews: 2345,
    stock: 5678,
    images: ['/product-1.jpg', '/product-2.jpg'],
    specs: {
      'Type': 'Basmati',
      'Weight': '5kg',
      'Origin': 'India',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_047',
    name: 'Organic Honey',
    description: 'Pure raw honey',
    category: 'Grocery',
    subcategory: 'Sweeteners',
    brand: 'Nature\'s Blessing',
    price: 599,
    originalPrice: 899,
    discount: 33,
    rating: 4.6,
    reviews: 1234,
    stock: 890,
    images: ['/product-2.jpg', '/product-3.jpg'],
    specs: {
      'Type': 'Organic',
      'Weight': '500g',
      'Purity': '100%',
    },
    warranty: '1 Year',
    delivery: 'Same Day',
  },
  {
    id: 'prod_048',
    name: 'Milk Powder',
    description: 'Nutritious milk powder',
    category: 'Grocery',
    subcategory: 'Dairy',
    brand: 'Amul',
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.4,
    reviews: 890,
    stock: 3456,
    images: ['/product-3.jpg', '/product-4.jpg'],
    specs: {
      'Type': 'Full Fat',
      'Weight': '400g',
      'Shelf Life': '18 months',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
  {
    id: 'prod_049',
    name: 'Olive Oil Premium',
    description: 'Extra virgin olive oil',
    category: 'Grocery',
    subcategory: 'Oils',
    brand: 'Borges',
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.7,
    reviews: 678,
    stock: 456,
    images: ['/product-4.jpg', '/product-5.jpg'],
    specs: {
      'Type': 'Extra Virgin',
      'Size': '500ml',
      'Origin': 'Spain',
    },
    warranty: '2 Years',
    delivery: '2 Days',
  },
  {
    id: 'prod_050',
    name: 'Coca Cola 1L Bottle',
    description: 'Refreshing beverage',
    category: 'Grocery',
    subcategory: 'Beverages',
    brand: 'Coca Cola',
    price: 59,
    originalPrice: 99,
    discount: 40,
    rating: 4.3,
    reviews: 1234,
    stock: 9876,
    images: ['/product-5.jpg', '/product-1.jpg'],
    specs: {
      'Size': '1L',
      'Type': 'Soft Drink',
      'Packaging': 'Bottle',
    },
    warranty: '6 Months',
    delivery: 'Same Day',
  },
];
export const PRODUCTS: Product[] = RAW_PRODUCTS.map((product, index) => ({
  ...product,

  categoryId: product.category
    .toLowerCase()
    .replace(/\s*&\s*/g, '-')
    .replace(/\s+/g, '-'),

  image: product.images[0],

  thumbnail: product.images[0],

  createdAt: new Date(),

  seller: {
    id: `seller_${String((index % 5) + 1).padStart(3, '0')}`,
    name: 'Visionary Store',
    verified: true,
    rating: 4.5,
  },

  seoTitle: product.name,
  seoDescription: product.description,

  isFeatured: product.rating >= 4.7,

  isTrending:
    product.reviews > 3000,

  isNewArrival: false,

  fastDelivery: [
    'Same Day',
    'Next Day',
  ].includes(product.delivery),

  badges: [
    ...(product.rating >= 4.7
      ? ['Top Rated']
      : []),
    ...(product.discount >= 40
      ? ['Great Deal']
      : []),
  ],

  color: product.specs.Color || '',
  size: product.specs.Size || '',

  sku: `SKU-${product.id.toUpperCase()}`,
}));

// Coupons
export const COUPONS: Coupon[] = [
  {
    id: 'coup_001',
    code: 'WELCOME50',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 500,
    maxDiscount: 500,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 1000,
    used: 234,
    isActive: true,
  },
  {
    id: 'coup_002',
    code: 'FLAT500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderValue: 2000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 500,
    used: 123,
    isActive: true,
  },
  {
    id: 'coup_003',
    code: 'ELECTRONICS25',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 5000,
    maxDiscount: 2000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 300,
    used: 145,
    isActive: true,
  },
  {
    id: 'coup_004',
    code: 'FASHION30',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 1000,
    maxDiscount: 1000,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 400,
    used: 267,
    isActive: true,
  },
  {
    id: 'coup_005',
    code: 'BOOKS40',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 300,
    maxDiscount: 300,
    expiryDate: new Date('2025-12-31'),
    usageLimit: 600,
    used: 389,
    isActive: true,
  },
];

// Default Addresses
export const DEFAULT_ADDRESSES: Address[] = [
  {
    id: 'addr_001',
    type: 'home',
    name: 'Home',
    phone: '9876543210',
    street: '123 Main Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    isDefault: true,
  },
  {
    id: 'addr_002',
    type: 'work',
    name: 'Office',
    phone: '9876543210',
    street: '456 Business Park',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400005',
    isDefault: false,
  },
];

// Filter options
export const PRICE_RANGES = [
  { label: 'Under ₹500', min: 0, max: 500 },
  { label: '₹500 - ₹2000', min: 500, max: 2000 },
  { label: '₹2000 - ₹10000', min: 2000, max: 10000 },
  { label: '₹10000 - ₹50000', min: 10000, max: 50000 },
  { label: 'Above ₹50000', min: 50000, max: Infinity },
];

export const BRANDS = Array.from(new Set(PRODUCTS.map(p => p.brand))).sort();
export const RATING_FILTERS = [
  { label: '4★ & above', min: 4 },
  { label: '3★ & above', min: 3 },
  { label: '2★ & above', min: 2 },
];
